import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Box, BranchingPathsUp, Download as DownloadIcon, Home, Layers, Palette, ShieldWarning } from "@solar-icons/react";
import { ConnectFlow, StackDiagram } from "@/components/Diagrams";
import { DetectedDownload } from "@/components/DetectedDownload";
import { ExternalLink, IndependenceNotice, ProductRow, Status } from "@/components/UI";
import { infoPages, pageBySlug } from "@/content/pages";
import { productById, products } from "@/content/products";

const special = ["ecosystem", "download", "404"];
export function generateStaticParams() { return [...products.map(p=>({slug:p.id})), ...infoPages.map(p=>({slug:p.slug})), ...special.map(slug=>({slug}))]; }
export async function generateMetadata({ params }: { params: Promise<{slug:string}> }): Promise<Metadata> { const {slug}=await params; const p=productById[slug]; const page=pageBySlug[slug]; const title=p?.name ?? (slug==="ecosystem"?"Glyph ecosystem":slug==="download"?"Download Glyph Wallet":slug==="404"?"Page not found":page?.title); const description=p?.summary ?? page?.description ?? (slug==="ecosystem"?"How Glyph products fit together across user, application, developer, and infrastructure layers.":slug==="404"?"The requested Glyph page could not be found.":"Verified Glyph Wallet downloads for Windows, macOS, and Linux."); if(!title) return {}; return {title,description,alternates:{canonical:`/${slug}`},robots:slug==="404"?{index:false,follow:false}:undefined,openGraph:{title,description,url:`/${slug}`,images:["/social/default.svg"]},twitter:{card:"summary_large_image",title,description,images:["/social/default.svg"]}} }

function ProductPage({ id }: {id:string}) { const p=productById[id]; const current=p.status==="Available"; return <main id="main" className={`product-page accent-${p.accent}`}><section className="page-hero section"><div><Status value={p.status}/><p className="kicker">{p.descriptor}</p><h1>{p.name}</h1><p className="lead">{p.summary}</p><div className="actions">{p.downloadUrl&&<ExternalLink className="button" href={p.downloadUrl}><DownloadIcon aria-hidden="true" />Download v0.14.3</ExternalLink>}{p.packageUrl&&<ExternalLink className="button" href={p.packageUrl}><Box aria-hidden="true" />View package</ExternalLink>}{p.repositoryUrl&&<ExternalLink className="button button-secondary" href={p.repositoryUrl}><BranchingPathsUp aria-hidden="true" />Repository</ExternalLink>}</div></div></section>
  {id==="wallet"&&<section className="section wallet-proof"><div className="wallet-window" role="img" aria-label="Abstracted composition showing the portrait proportions and navigation structure of the Glyph Wallet desktop application"><div className="wallet-chrome"><span/><span/><span/></div><div className="wallet-ui"><aside>G.<i/><i/><i/><i/></aside><div><small>PRIMARY VAULT</small><h3>Local control</h3><p>Review every request before signing.</p><div className="wallet-actions"><span>Send</span><span>Receive</span><span>Stake</span></div><div className="wallet-rows"><span/><span/><span/></div></div></div></div><div><h2>Desktop software, not a browser extension.</h2><p>Glyph Wallet runs as a Tauri desktop application. The official repository describes encrypted local vaults, native signing, replay protection, and a constrained renderer-to-Rust boundary.</p><ul className="check-list">{p.capabilities.map(x=><li key={x}>{x}</li>)}</ul></div></section>}
  {id==="connect"&&<><section className="section"><div className="section-heading"><h2>A request you can inspect</h2><p>The example follows the published v2.0.0 API and includes a rejection path.</p></div><pre className="code-block"><code>{`import { createConnectRequest, glyphRequest } from "@glyph-oss/connect";\n\ntry {\n  const result = await glyphRequest(createConnectRequest({\n    type: "connect",\n    dapp: { name: "My App", origin: "https://my.app" },\n    permissions: ["transfer", "sign_message"],\n  }));\n\n  if (result.status === "rejected") {\n    console.info(result.reason);\n  }\n} catch (error) {\n  console.error("Glyph Wallet could not be opened", error);\n}`}</code></pre></section><section className="section"><ConnectFlow/></section></>}
  {!current&&<section className="section availability"><div><h2>What exists today</h2><p>The product direction and ecosystem role are defined. No public release, package, endpoint, command syntax, or complete documentation is available yet.</p></div><div><h2>What will guide the work</h2><ul>{p.principles.map(x=><li key={x}>{x}</li>)}</ul></div></section>}
  <section className="section split"><div><p className="kicker">Ecosystem role</p><h2>{current?"A working part of the system.":"A stated part of the future system."}</h2></div><div><p>{p.principles.join(". ")}.</p><dl className="metadata-list"><div><dt>Status</dt><dd>{p.status}</dd></div><div><dt>License</dt><dd>{p.licenseStatus} · {p.licenseName}</dd></div><div><dt>Public availability</dt><dd>{current?"Available now":"Not available yet"}</dd></div></dl></div></section>
  <section className="section"><div className="section-heading"><h2>Related products</h2></div><div className="product-list">{p.related.map(x=><ProductRow key={x} product={productById[x]}/>)}</div></section><IndependenceNotice/></main> }

function Ecosystem() { return <main id="main"><section className="page-hero section"><div><p className="kicker">Glyph ecosystem</p><h1>Software organized by responsibility.</h1><p className="lead">The product family connects application intent, developer workflows, infrastructure, and user-controlled approval.</p></div></section><section className="section section-dark"><StackDiagram/></section><section className="section"><div className="section-heading"><h2>How a dApp reaches Wallet</h2></div><ConnectFlow/></section><section className="section"><div className="section-heading"><h2>Current and future architecture</h2><p>Available products work today. In-development and planned products describe the intended system without implying availability.</p></div><div className="product-list">{products.map(p=><ProductRow key={p.id} product={p}/>)}</div></section><IndependenceNotice/></main> }
function Download() { return <main id="main"><section className="page-hero section download-hero"><div><Status value="Available"/><p className="kicker">Glyph Wallet v0.14.3</p><h1>Choose your platform.</h1><p className="lead">Verified stable release assets are published on GitHub. Prereleases are not selected automatically.</p><DetectedDownload /></div></section><section className="section downloads"><a className="download-windows" href="https://github.com/glyphq/wallet/releases/download/v0.14.3/Glyph_0.14.3_x64-setup.exe"><b>Windows</b><span>64-bit installer · .exe</span><i>Download ↗</i></a><a className="download-macos" href="https://github.com/glyphq/wallet/releases/download/v0.14.3/Glyph_0.14.3_universal.dmg"><b>macOS</b><span>Universal · .dmg</span><i>Download ↗</i></a><a className="download-linux" href="https://github.com/glyphq/wallet/releases/tag/v0.14.3"><b>Linux</b><span>AppImage · deb · rpm</span><i>Choose package ↗</i></a></section><section className="section split"><h2>Release verification</h2><div><p>The release includes platform checksum files and updater signatures. Use the GitHub release page to review every asset before installation.</p><ExternalLink className="quiet-link" href="https://github.com/glyphq/wallet/releases/tag/v0.14.3">View complete release</ExternalLink></div></section><IndependenceNotice/></main> }
function Explicit404() { return <main id="main" className="not-found"><span>404 / UNKNOWN ROUTE</span><h1>This structure does not resolve.</h1><p>The address may have changed, or the page may never have existed.</p><div className="actions"><Link className="button" href="/"><Home aria-hidden="true" />Return home</Link><Link className="button button-secondary" href="/ecosystem"><Layers aria-hidden="true" />Explore products</Link></div></main> }
function Info({slug}:{slug:string}) { const page=pageBySlug[slug]; return <main id="main"><section className="page-hero section"><div><p className="kicker">Glyph / {slug.replace("-"," ")}</p><h1>{page.title}</h1><p className="lead">{page.intro}</p>{slug==="security"&&<ExternalLink className="button" href="https://github.com/glyphq/wallet/security/advisories/new"><ShieldWarning aria-hidden="true" />Report a vulnerability</ExternalLink>}{slug==="brand"&&<ExternalLink className="button" href="https://branding.glyphq.org"><Palette aria-hidden="true" />Open brand resources</ExternalLink>}</div></section><section className="section prose-sections">{page.sections.map((s,i)=><article key={s.title}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{s.title}</h2><p>{s.body}</p>{s.items&&<ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>}</div></article>)}</section>{slug==="developers"&&<section className="section"><ConnectFlow/><pre className="code-block"><code>npm install @glyph-oss/connect</code></pre></section>}{slug==="roadmap"&&<section className="section"><div className="product-list">{products.map(p=><ProductRow key={p.id} product={p}/>)}</div></section>}<IndependenceNotice/></main> }
export default async function SlugPage({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; if(productById[slug]) return <ProductPage id={slug}/>; if(slug==="ecosystem") return <Ecosystem/>; if(slug==="download") return <Download/>; if(slug==="404") return <Explicit404/>; if(pageBySlug[slug]) return <Info slug={slug}/>; notFound(); }
